# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - helm-repo-operator.yaml
#   - operator.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opensearch-operator
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./source
  prune: true
  sourceRef:
    kind: GitRepository
    name: opensearch-operator
  targetNamespace: default