apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest-gateway
spec: 
  config: |
    receivers:
      otlp:
        protocols:
          grpc:            
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
    exporters:
      otlp/data-prepper:
        endpoint: data-prepper.devops-logging-opensearch.svc.cluster.local:21890
        tls:
          insecure: true  
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging, otlp/data-prepper]
          